/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/plaque.glb --transform --simplify=false 
Files: public/plaque.glb [273.35KB] > C:\Users\timot\Documents\Synchro\Projets\dashboard\frontend\plaque-transformed.glb [28.96KB] (89%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/plaque-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.plaque.geometry} material={materials.Mat_Plaque} />
      <mesh geometry={nodes.bouton1.geometry} material={nodes.bouton1.material} position={[-2.853, 0.485, -7.38]} />
    </group>
  )
}

useGLTF.preload('/plaque-transformed.glb')
