
services:
  # --- LE BACKEND ---
  backend:
    build: 
      context: ./backend # Chemin vers ton dossier backend
    container_name: dashboard-api
    restart: always
    ports:
      - "8085:8085"
    env_file: .env # Il lira tes clés Meross ici
    volumes:
      - dashboard_db:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

  # --- LE FRONTEND ---
  frontend:
    build:
      context: ./frontend # Chemin vers ton dossier frontend
    container_name: dashboard-ui
    restart: always
    ports:
      - "8084:8084"


volumes:
  dashboard_db: